CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Email] VARCHAR(250) NOT NULL,
	[Pwd] VARBINARY(64) NOT NULL,
	[Nickname] VARCHAR(50) NOT NULL,
	[Salt] VARCHAR(100) NOT NULL, 
    [IsAdmin] BIT DEFAULT 0
)
